"""Pytest configuration and fixtures for LocalStack testing with CDK infrastructure."""

import json
import os
import boto3
import pytest
from botocore.config import Config


def pytest_configure(config):
    """
    Configure pytest to enforce 90% coverage threshold for all tests.
    LocalStack tests must meet the 90% requirement per challenge requirements.
    """
    # Always enforce 90% coverage threshold
    config.option.cov_fail_under = 90

LOCALSTACK_ENDPOINT = os.getenv("LOCALSTACK_ENDPOINT", "http://localhost:4566")
AWS_REGION = os.getenv("AWS_REGION", "us-east-1")
TESTS_DIR = os.path.dirname(__file__)
OUTPUTS_FILE = os.path.join(TESTS_DIR, "localstack-outputs.json")


@pytest.fixture(scope="session")
def infrastructure_outputs():
    """
    Read CDK stack outputs from file (generated by setup script).

    Returns:
        Dictionary with queue_url, dlq_url, and api_url from CDK stacks
    """
    if not os.path.exists(OUTPUTS_FILE):
        pytest.skip(
            "CDK infrastructure not deployed to LocalStack. "
            "Run: ./scripts/setup-localstack-test.sh"
        )

    with open(OUTPUTS_FILE) as f:
        all_outputs = json.load(f)

    # Extract outputs from the JSON structure
    # CDK outputs are typically nested by stack name
    queue_url = None
    dlq_url = None
    api_url = None

    # Try to find outputs in various possible formats
    if isinstance(all_outputs, dict):
        # Check if it's a direct output format
        if "TaskManagementShared-test" in all_outputs:
            stack_outputs = all_outputs["TaskManagementShared-test"]
            queue_url = stack_outputs.get("QueueUrl")
            dlq_url = stack_outputs.get("DeadLetterQueueUrl")
        else:
            # Try direct keys
            queue_url = all_outputs.get("QueueUrl")
            dlq_url = all_outputs.get("DeadLetterQueueUrl")

        # Get API URL
        if "TaskManagementApi-test" in all_outputs:
            api_outputs = all_outputs["TaskManagementApi-test"]
            api_url = api_outputs.get("ApiUrl") or api_outputs.get("ApiEndpoint")
        else:
            api_url = all_outputs.get("ApiUrl") or all_outputs.get("ApiEndpoint")

    return {
        "queue_url": queue_url,
        "dlq_url": dlq_url,
        "api_url": api_url,
    }


@pytest.fixture(scope="session")
def sqs_client():
    """
    Create SQS client pointing to LocalStack.

    Returns:
        boto3 SQS client configured for LocalStack
    """
    config = Config(region_name=AWS_REGION)
    return boto3.client(
        "sqs",
        config=config,
        endpoint_url=LOCALSTACK_ENDPOINT,
        aws_access_key_id="test",
        aws_secret_access_key="test",
    )


@pytest.fixture(scope="function")
def reset_processed_tasks():
    """Reset the processed tasks cache for idempotency testing."""
    from src.processor.handler import _processed_tasks

    _processed_tasks.clear()
    yield
    _processed_tasks.clear()
